apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost-blog
  labels:
    app: ghost-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ghost-blog
  template:
    metadata:
      labels:
        app: ghost-blog
    spec:
      volumes:
        - name: ghost-blog-volume-storage
          persistentVolumeClaim:
            claimName: ghost-blog-volume-claim
      containers:
        - name: ghost
          image: "ghost:3.42.5-alpine"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/var/lib/ghost/content"
              name: ghost-blog-volume-storage
          ports:
            - containerPort: 2368
          env:
            - name: url
              value: "http://life-with-cirrhos.is"  