apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-blog-content
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage